FROM node:16.14.0-alpine
WORKDIR /usr/src/app

COPY gateway/package.json gateway/package-lock.json ./

RUN npm i

COPY ./gateway .

RUN npm run build

ENV NODE_ENV production
CMD [ "node", "dist/index.js" ]