# CASSANDRA_USER: "cassandra" 
      #CASSANDRA_PASSWORD: "cassandra"

apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-depl
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events
  template:
    metadata:
      labels:
        app: events
    spec:
      containers:
        - name: events
          image: sijibomi242/eventer-events-pre-prod:latest #TODO: image pull secret to auth with docker
          env:
            - name: SECRET_KEY
              valueFrom: 
                secretKeyRef:
                  name: events-db-config #name of secret to get value from
                  key: SECRET_KEY #name of key in secret
            - name: SQL_ENGINE
              valueFrom: 
                secretKeyRef:
                  name: events-db-config
                  key: SQL_ENGINE
            - name: SQL_DATABASE
              valueFrom: 
                secretKeyRef:
                  name: events-db-config
                  key: SQL_DATABASE
            - name: TEST_NAME
              valueFrom:
                secretKeyRef:
                  name: events-db-config
                  key: TEST_NAME
            - name: SQL_HOST
              valueFrom:
                secretKeyRef:
                  name: events-db-config
                  key: SQL_HOST
            - name: USER_NAME
              valueFrom:
                secretKeyRef:
                  name: events-db-config
                  key: USER_NAME
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: events-db-config
                  key: PASSWORD
            - name: RABBITS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbits-config
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbits-config
                  key: RABBITMQ_DEFAULT_PASS
            - name: RABBITS_HOST
              valueFrom:
                secretKeyRef:
                  name: rabbits-config
                  key: RABBITS_HOST 
            - name: RABBITS_PORT
              valueFrom:
                secretKeyRef:
                  name: rabbits-config
                  key: RABBITS_PORT
            - name: ALLOWED_HOSTS
              valueFrom:
                secretKeyRef:
                  name: events-db-config
                  key: ALLOWED_HOSTS
            

---
apiVersion: v1
kind: Service
metadata:
  name: events-loadbalancer
  namespace: staging
spec:
  type: LoadBalancer
  ports:
  - port: 80
  targetPort: 8080
  selector:
  app: events