apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-depl
  namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: sijibomi242/eventer-gateway-pre-prod:latest #TODO: image pull secret to auth with docker
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: image-secret
          env:
            - name: REDIS_URL
              valueFrom: 
                secretKeyRef:
                  name: redis-config
                  key: REDIS_URL

