apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-db-depl
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-db
  template:
    metadata:
      labels:
        app: users-db
    spec:
      containers:
        - name: users-db
          image: postgres:13-alpine
          env:
            - name: POSTGRES_DB #name of env i.e pod will access the env with this name
              valueFrom: 
                secretKeyRef:
                  name: users-db-config #name of secret to get value from 
                  key: POSTGRES_DB #name of key in secret
            - name: POSTGRES_USER
              valueFrom: 
                secretKeyRef:
                  name: users-db-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: users-db-config
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service 
metadata:
  name: users-db-srv
  namespace: staging
spec:
  selector:
    app: users-db
  ports:
    - name: db
      protocol: TCP
      port: 5432
      targetPort: 5432