apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-depl
  namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: sijibomi242/eventer-users-pre-prod:latest #TODO: image pull secret to auth with docker
          env:
            - name: POSTGRES_DB #name of env i.e pod will access the env with this name
              valueFrom: 
                secretKeyRef:
                  name: users-db-config #name of secret to get value from
                  key: POSTGRES_DB #name of key in secret
            - name: POSTGRES_USER 
              valueFrom: 
                secretKeyRef:
                  name: users-db-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: users-db-config
                  key: POSTGRES_PASSWORD
            - name: REDIS_URL
              valueFrom: 
                secretKeyRef:
                  name: redis-config
                  key: REDIS_URL

---

apiVersion: v1
kind: Service
metadata:
  name: users-srv
spec:
  selector:
    app: users
  ports:
    - name: users
      protocol: TCP
      port: 80
      targetPort: 4000




 