apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-depl
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: sijibomi242/eventer-users-pre-prod:latest #TODO: image pull secret to auth with docker
          env:
            - name: POSTGRES_DB #name of env i.e pod will access the env with this name
              valueFrom: 
                secretKeyRef:
                  name: USERS_DB_CONFIG #name of secret to get value from
                  key: POSTGRES_DB #name of key in secret
            - name: POSTGRES_USER
              valueFrom: 
                secretKeyRef:
                  name: USERS_DB_CONFIG
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: USERS_DB_CONFIG
                  key: POSTGRES_PASSWORD
            - name: REDIS_URL
              valueFrom: 
                secretKeyRef:
                  name: REDIS_CONFIG
                  key: REDIS_URL

---
apiVersion: v1
kind: Service
metadata:
  name: users-loadbalancer
  namespace: staging
spec:
  type: LoadBalancer
  ports:
  - port: 80
  targetPort: 4000 
  selector:
  app: users


