FROM node:16.14.0-alpine
WORKDIR /usr/src/app

COPY users/package.json users/package-lock.json ./

RUN npm i

COPY ./users .

RUN npm run build

ENV NODE_ENV production
CMD [ "node", "dist/index.js" ]