name: gateway:tests
on:
  push:
    branches:
      - dev
    paths:
      - 'gateway/**'
  pull_request:
    branches:
      - dev
    paths:
      - 'gateway/**'
jobs:
  test:
    name: test-gateway
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./gateway
    steps:
      - uses: actions/checkout@v2
      - uses: cd gateway && npm install && npm run test:ci
      - run:  cd gateway && docker build -t sijibomi242/eventer-gateway-dev .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push sijibomi242/eventer-gateway-dev
