name: events:tests
on:
  push:
    branches:
      - dev
    paths:
      - 'events/**'
  pull_request:
    branches:
      - dev
    paths:
      - 'events/**'
jobs:
  test:
    name: test-events
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./events
    env:
      SECRET_KEY: test-key-not-good-maybe-make-one-better
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          python manage.py test
      - run: docker build -t sijibomi242/eventer-events-dev:latest -t sijibomi242/eventer-events-dev:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5} .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push sijibomi242/eventer-events-dev --all-tags
      - name: trigger jenkins build Job
        uses: appleboy/jenkins-action@master
        with:
          url: ${{ secrets.JENKINS_URL }} 
          user: "username"
          token: ${{ secrets.JENKINS_TOKEN}}
          job: "eventer-events-dev"
      