name: gateway:tests
on:
  push:
    branches:
      - dev
    paths:
      - 'gateway/**'
  pull_request:
    branches:
      - dev
    paths:
      - 'gateway/**'
jobs:
  test:
    name: test-gateway
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./gateway
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t sijibomi242/eventer-gateway-dev:latest -t sijibomi242/eventer-gateway-dev:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5} .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push sijibomi242/eventer-gateway-dev --all-tags
      - name: trigger jenkins build Job
        uses: appleboy/jenkins-action@master
        with:
          url: "http://34.66.4.108:8080"
          user: "username"
          token: ${{ secrets.JENKINS_TOKEN}}
          job: "eventer-gateway-dev"
