name: gateway:tests
on:
  push:
    branches:
      - dev
    paths:
      - 'gateway/**'
  pull_request:
    branches:
      - dev
    paths:
      - 'gateway/**'
jobs:
  test:
    name: test-gateway
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./gateway
    steps:
      - uses: actions/checkout@v2
      - run:  docker build -f Dockerfile \
            -t sijibomi242/eventer-gateway-dev:latest \
            -t sijibomi242/eventer-gateway-dev:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5} \
            .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push sijibomi242/eventer-gateway-dev --all-tags
      - name: Create Pull Request
        id: sxxidhuhfiehijij
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.TOKEN }}
          commit-message: ${{ github.event.head_commit.message }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: dev
          delete-branch: false
          title: ${{ github.event.head_commit.message }}
          labels: |
            report
            automated pr
          assignees: sijibomii
          reviewers: sijibomii
          base: pre-prod
      - name: trigger jenkins build Job
        uses: appleboy/jenkins-action@master
        with:
          url: "tf-lb-20220325120129809100000001-2104115208.us-east-1.elb.amazonaws.com"
          user: "jenkins"
          token: ${{ secrets.JENKINS_TOKEN}}
          job: "eventer-gateway-dev"
