name: users:tests
on:
  push:
    branches:
      - dev
    paths:
      - 'users/**'
  pull_request:
    branches:
      - dev
    paths:
      - 'users/**' 
jobs:
  test:
    name: test-users
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./users
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t sijibomi242/eventer-users-dev:latest -t sijibomi242/eventer-users-dev:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5} .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push sijibomi242/eventer-users-dev --all-tags
      - name: trigger jenkins build Job
        uses: appleboy/jenkins-action@master
        with:
          url: ${{ secrets.JENKINS_URL }} 
          user: "username"
          token: ${{ secrets.JENKINS_TOKEN }}
          job: "eventer-users-dev"
